FROM python:3.8-slim

WORKDIR /backend/ml_model

COPY ./requirements.txt .

RUN python3 install --upgrade pip \
    && pip install -r requirements.txt 

#Copy the Entire Application
COPY ./ml_model . 

RUN python3 db.py

CMD ["python3", "stock_market_prediction.py"]

